### PR TITLE
Largest rectangle in Histogram

### PR DESCRIPTION
**Pull request by Rishav17102003**
Please merge my pull request

### CODE REVIEW

**Comment by tanus786** [comment]
Please give this repo a star and follow me for follow back 😊

**Comment by tanus786** [comment]
bhai kya kra ye tune
sari files kyu delete krdi pgl h kya?

**Comment by Rishav17102003** [comment]
are maine nahi delete kari mere laptop me clone hi nhi hua tha
git status se dekha to delete bta rha tha sorry,
really sorry

**Comment by Rishav17102003** [comment]
mai abse branch bnake pull request daalunga sorry, really sorry

**Comment by Rishav17102003** [comment]
mera pull request aapne close kar diya sorry maaf kar do

**Comment by Rishav17102003** [comment]
stock span waala
sorry maaf kar doooooooooooooooooooooooooooooo

**Pull request merged**
