### PR TITLE
Create Flatten binary tree to linked list.cpp

### PR DESCRIPTION
**Pull request by kunalkabra46**

### CODE REVIEW

**Comment by tanus786** [comment]
Merged you PR✨

**Comment by kunalkabra46** [comment]
please add hacktoberfest accepted label...

**Comment by kunalkabra46** [comment]
i have starred the repo...please add label...

**Comment by kunalkabra46** [comment]
hey @tanus786  please do the needful...add hacktoberfest accepted label

**Comment by tanus786** [comment]
Where should i add this label?

**Pull request merged**
