### PR TITLE
median of 2 sorted array problem of leetcode

### PR DESCRIPTION
**Pull request by Stormchaser1o1**

### CODE REVIEW

**Comment by tanus786** [comment]
Great work please give this repo a star and follow me for follow back 😊

**Comment by YOGENDERSS** [comment]
@tanus786 did it

**Comment by YOGENDERSS** [comment]
😃😊

**Comment by Stormchaser1o1** [comment]
@tanus786 thanks. i have followed you and give star to the repo as well.😊😃

**Pull request merged**
