### PR TITLE
Create a Bucket sort in c++

### PR DESCRIPTION
**Pull request by Aman736**
create a bucket sort in easyest method please approve it..

### CODE REVIEW

**Comment by tanus786** [comment]
Great work please give this repo a star and follow me for follow back 😊

**Comment by Aman736** [comment]
thank You and done... :)

**Comment by Aman736** [comment]
image

it shows me this why..

**Comment by tanus786** [comment]
Is it get merged?

**Comment by Aman736** [comment]
yes ThankYou

**Comment by tanus786** [comment]
Please give this repo a star ✨
Thank you ☺️

**Comment by Aman736** [comment]
i have one question, my only two repo is count some are excluded and some are not-Accepted. Can i do other question on your repo should it countable on hacktoberfest ...???

**Pull request merged**
