### PR TITLE
Solution | Merge sorted lists 

### PR DESCRIPTION
**Pull request by ak84349**

### CODE REVIEW

**Comment by tanus786** [comment]
Great work @ak84349  please give this repo a star if it really helped you to complete your PR.
Also follow me for follow back if you want to  get connected with me for any such open source contribution program. Thank you 😊

**Comment by ak84349** [comment]
Hey thanks @tanus786, Can we do multiple contribution to this repo?
I wanted to add more solutions in this repo.
Will that be ok?

**Comment by tanus786** [comment]
Yeah sure go for it✨

**Comment by tanus786** [comment]
But make sure to give this repo a star if it helped you and follow me for follow back and to get updated about such programs ✨

**Pull request merged**
